version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./stormcommand.db:/app/stormcommand.db
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 wsgi:app